language: node_js
node_js:
  - "7.2"
script:
  - echo "Deploying!"
install:
  - npm install -g firebase-tools
  - npm install -g browserify
after_success:
  - firebase use default
  - firebase deploy --token $FIREBASE_TOKEN
