language: node_js
node_js:
  - "7.2"
script:
  - echo "Deploying!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase use --token $FIREBASE_TOKEN default
  - firebase deploy --non-interactive --token $FIREBASE_TOKEN
